### ISSUE TITLE
GraphQL`mutation CreateUser`で`Invalid this.prismaService.user.create()`エラーが発生する問題を解決する

### ISSUE THREAD

**Issue by ReoHakase** [3I-shikosai32/shikosai32-server#282]
# 概要
`prisma`で`user.create()`するときに、`User`のフィールドとして依然と`character`を渡してしまっているみたいです(?)
# エラー情報
## URQLを使用した際のエラー時の`error`レスポンス
```js
{
  value: {
    name: "CombinedError",
    graphQLErrors: [
      {
        message: "\nInvalid `this.prismaService.user.create()` invocation in\n/opt/render/project/src/src/module/user/repository/user.repository.ts:26:55\n\n  23 }\n  24 \n  25 async create<T extends Create>(args: StrictPropertyCheck<T, Create>) {\n→ 26   const createdUser = await this.prismaService.user.create({\n         data: {\n           character: 'CAT',\n           ~~~~~~~~~\n           email: 'reonaldhkt@gmail.com',\n           id: 'wpHpR8NmrwOX86W4tsAZcDDMLcr1',\n           name: '白田連大（Reo Hakuta）',\n           role: 'USER',\n           characterStatuses: {\n             create: {\n               character: 'CAT',\n               iconUrl: 'https://firebasestorage.googleapis.com/v0/b/i-shikosai32.appspot.com/o/sys%2Fcharacter%2Fcat%2Ficon.svg%3Falt%3Dmedia',\n               avatarUrl: 'https://firebasestorage.googleapis.com/v0/b/i-shikosai32.appspot.com/o/sys%2Fcharacter%2Fcat%2Fbase.svg%3Falt%3Dmedia',\n               isActive: true,\n               itemIds: [\n                 '634a77029b86445083519a23',\n                 '634a77029b86445083519a24',\n                 '634a77029b86445083519a25',\n                 '634a77029b86445083519a26'\n               ],\n               items: {\n                 connect: [\n                   {\n                     id: '634a77029b86445083519a23'\n                   },\n                   {\n                     id: '634a77029b86445083519a24'\n                   },\n                   {\n                     id: '634a77029b86445083519a25'\n                   },\n                   {\n                     id: '634a77029b86445083519a26'\n                   }\n                 ]\n               }\n             }\n           }\n         }\n       })\n\nUnknown arg `character` in data.character for type UserCreateInput. Available args:\n\ntype UserCreateInput {\n  id?: String\n  name: String\n  email: String\n  role?: Role\n  totalPointDay1?: Int\n  totalPointDay2?: Int\n  consumablePoint?: Int\n  participateGame?: Game\n  pullableGachaTimes?: Int\n  characterStatuses?: CharacterStatusCreateNestedManyWithoutUserInput\n  giftHistories?: GiftHistoryCreateNestedManyWithoutUserInput\n  createdAt?: DateTime\n}\n\n",
        path: [
          "createUser"
        ],
        extensions: {
          code: "INTERNAL_SERVER_ERROR",
          exception: {
            clientVersion: "4.4.0",
            stacktrace: [
              "Error: ",
              "Invalid `this.prismaService.user.create()` invocation in",
              "/opt/render/project/src/src/module/user/repository/user.repository.ts:26:55",
              "",
              "  23 }",
              "  24 ",
              "  25 async create<T extends Create>(args: StrictPropertyCheck<T, Create>) {",
              "→ 26   const createdUser = await this.prismaService.user.create({",
              "         data: {",
              "           character: 'CAT',",
              "           ~~~~~~~~~",
              "           email: 'reonaldhkt@gmail.com',",
              "           id: 'wpHpR8NmrwOX86W4tsAZcDDMLcr1',",
              "           name: '白田連大（Reo Hakuta）',",
              "           role: 'USER',",
              "           characterStatuses: {",
              "             create: {",
              "               character: 'CAT',",
              "               iconUrl: 'https://firebasestorage.googleapis.com/v0/b/i-shikosai32.appspot.com/o/sys%2Fcharacter%2Fcat%2Ficon.svg%3Falt%3Dmedia',",
              "               avatarUrl: 'https://firebasestorage.googleapis.com/v0/b/i-shikosai32.appspot.com/o/sys%2Fcharacter%2Fcat%2Fbase.svg%3Falt%3Dmedia',",
              "               isActive: true,",
              "               itemIds: [",
              "                 '634a77029b86445083519a23',",
              "                 '634a77029b86445083519a24',",
              "                 '634a77029b86445083519a25',",
              "                 '634a77029b86445083519a26'",
              "               ],",
              "               items: {",
              "                 connect: [",
              "                   {",
              "                     id: '634a77029b86445083519a23'",
              "                   },",
              "                   {",
              "                     id: '634a77029b86445083519a24'",
              "                   },",
              "                   {",
              "                     id: '634a77029b86445083519a25'",
              "                   },",
              "                   {",
              "                     id: '634a77029b86445083519a26'",
              "                   }",
              "                 ]",
              "               }",
              "             }",
              "           }",
              "         }",
              "       })",
              "",
              "Unknown arg `character` in data.character for type UserCreateInput. Available args:",
              "",
              "type UserCreateInput {",
              "  id?: String",
              "  name: String",
              "  email: String",
              "  role?: Role",
              "  totalPointDay1?: Int",
              "  totalPointDay2?: Int",
              "  consumablePoint?: Int",
              "  participateGame?: Game",
              "  pullableGachaTimes?: Int",
              "  characterStatuses?: CharacterStatusCreateNestedManyWithoutUserInput",
              "  giftHistories?: GiftHistoryCreateNestedManyWithoutUserInput",
              "  createdAt?: DateTime",
              "}",
              "",
              "",
              "    at Document.validate (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:29297:20)",
              "    at serializationFn (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:31876:19)",
              "    at runInChildSpan (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:25100:12)",
              "    at PrismaService._executeRequest (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:31883:31)",
              "    at consumer (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:31810:23)",
              "    at /opt/render/project/src/node_modules/@prisma/client/runtime/index.js:31815:51",
              "    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)",
              "    at /opt/render/project/src/node_modules/@prisma/client/runtime/index.js:31815:29",
              "    at runInChildSpan (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:25100:12)",
              "    at PrismaService._request (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:31812:22)"
            ]
          }
        }
      }
    ],
    response: {}
  }
}
```
## 送られた`mutation`
URQL Devtools から確認したものです
```gql
mutation CreateUser($data: UserCreateInput!) {
  createUser(data: $data) {
    createdAt
    id
    name
    __typename
  }
}
```
## 送られた`mutation`の`variable`
```js
{
  data: {
    id: "wpHpR8NmrwOX86W4tsAZcDDMLcr1",
    name: "白田連大（Reo Hakuta）",
    email: "reonaldhkt@gmail.com",
    character: "CAT"
  }
}
```
![image](https://user-images.githubusercontent.com/16751535/196241547-905f5413-b9dc-46fe-84dd-1ab2045a763d.png)

**Comment by dino3616** [comment]
これはもうね、余剰プロパティチェックを怠っている言語機能がｗ(ry
解決策としては、infraと接続してる層ではスプレッド演算子を使わないってのが多分一番いいですね。
